### ISSUE TITLE
Morning Session: Code Review

### ISSUE THREAD

**Issue by faizi2500** [julie-ify/Todo-list-review#2]
## Amazing Job With The Project ## 
However there are few suggestions that we, in the morning team came up with. We think it will help you improve your project. 

- On deleting the tasks, indexes are not being updated. Try adding a for each loop when you restore the updated array of tasks. 
https://github.com/julie-ify/Todo-list-review/blob/5854edd4f0adfb7c328d4f1c0ed003d05f4af906/src/completed.js#L9-L13

- Your JS module files, check.js, has CSS imported independently. Verify if everything works without the import.
https://github.com/julie-ify/Todo-list-review/blob/5854edd4f0adfb7c328d4f1c0ed003d05f4af906/src/check.js#L1 

Your project is great. 
Happy Coding. 
> You can leave us a comment here in case there is anything unclear in the issue.

**Comment by julie-ify** [comment]
Thanks, guys for reviewing my code!!

I just removed the `import './style.css';` and the app still works fine.
The indexes of the tasks are updated when a task is deleted.

Thanks, team 👍
